version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: llm_eval_postgres
    environment:
      POSTGRES_DB: llm_eval
      POSTGRES_USER: llm_user
      POSTGRES_PASSWORD: llm_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - llm_eval_network
    restart: unless-stopped

  # Backend API
  backend:
    image: 28101995/llm-eval-backend:latest
    container_name: llm_eval_backend
    environment:
      - DATABASE_URL=postgresql://llm_user:llm_password@postgres:5432/llm_eval
      - SECRET_KEY=change-this-in-production
      - ENVIRONMENT=production
      - CORS_ORIGINS=http://localhost:3000,http://localhost:80,http://frontend:80
    volumes:
      - ./uploads:/app/uploads
      - ./chroma_db:/app/chroma_db
    ports:
      - "8000:8000"
    networks:
      - llm_eval_network
    depends_on:
      - postgres
    restart: unless-stopped

  # Frontend
  frontend:
    image: y28101995/llm-eval-frontend:latest
    container_name: llm_eval_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - NODE_ENV=production
    ports:
      - "80:80"
    networks:
      - llm_eval_network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  llm_eval_network:
    driver: bridge
