version: '3.8'

services:
  # Backend with development settings
  backend:
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - CORS_ORIGINS=http://localhost:3000,http://localhost:80,http://frontend:80
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./backend/chroma_db:/app/chroma_db
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"

  # Frontend with development settings
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "start"]

  # PostgreSQL with development settings
  postgres:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_USER=dev_user
      - POSTGRES_DB=llm_eval_dev


