name: Build and Push Docker Images (Simple)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual trigger

env:
  REGISTRY: docker.io
  IMAGE_NAME_BACKEND: ${{ secrets.DOCKERHUB_USERNAME }}/promptpit-backend
  IMAGE_NAME_FRONTEND: ${{ secrets.DOCKERHUB_USERNAME }}/promptpit-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ env.IMAGE_NAME_BACKEND }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ${{ env.IMAGE_NAME_FRONTEND }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Output success message
      run: |
        echo "✅ Successfully built and pushed images to Docker Hub!"
        echo "Backend: ${{ env.IMAGE_NAME_BACKEND }}:latest"
        echo "Frontend: ${{ env.IMAGE_NAME_FRONTEND }}:latest"
        echo ""
        echo "Users can now run: docker-compose -f docker-compose.prod.yml up -d"
